### ISSUE TITLE
Android can't store large email (test on a email with 4MB txt file attachment)

### ISSUE THREAD

**Issue by jupancs** [jupancs/MailSync#43]
If you received an email with a large attachment, I tested on an email with a 4MB text file, the part of traces is shown below. The storing process went normally after the error message, but when you synchronize with the laptop, you will get probe Interest timed out. 

```
I/System.out: ------------- Client -------------
I/System.out: ************* Google*************
I/System.out: C: tag=1, command=CAPABILITY
    IMAP Line received : <1 CAPABILITY>
I/System.out: IMAP Line received : <
    >
    proxySelection = 2; no network service selected, use local service
    local service_ capability response: CAPABILITY IMAP4rev1 LITERAL+ SORT UIDPLUS
I/System.out: C: tag=2, command=ID
    IMAP Line received : <2 ID >
I/System.out: C: tag=3, command=LOGIN
I/System.out: IMAP Line received : <3 LOGIN >
I/System.out: IMAP Line received : <jupan686@gmail.com "pjokk19940722"\r\n>
I/System.out: Login: jupan686@gmail.com, pjokk19940722
I/System.out: C: tag=4, command=CAPABILITY
I/System.out: IMAP Line received : <4 CAPABILITY>
    IMAP Line received : <
    >
    proxySelection = 2; no network service selected, use local service
I/System.out: local service_ capability response: CAPABILITY IMAP4rev1 LITERAL+ SORT UIDPLUS
I/System.out: C: tag=5, command=NAMESPACE
I/System.out: IMAP Line received : <5 NAMESPACE>
I/System.out: C: tag=6, command=NOOP
I/System.out: IMAP Line received : <6 NOOP>
    IMAP Line received : <
I/System.out: >
I/System.out: C: tag=7, command=LIST
    IMAP Line received : <7 LIST >
I/System.out: IMAP Line received : <"" "*"\r\n>
I/System.out: -----------------------------------
I/System.out: ------------- Client -------------
I/System.out: ************* Google*************
I/System.out: C: tag=1, command=CAPABILITY
    IMAP Line received : <1 CAPABILITY>
I/System.out: IMAP Line received : <
    >
    proxySelection = 2; no network service selected, use local service
    local service_ capability response: CAPABILITY IMAP4rev1 LITERAL+ SORT UIDPLUS
I/System.out: C: tag=2, command=ID
    IMAP Line received : <2 ID >
I/System.out: C: tag=3, command=LOGIN
I/System.out: IMAP Line received : <3 LOGIN >
I/System.out: IMAP Line received : <jupan686@gmail.com "pjokk19940722"\r\n>
    Login: jupan686@gmail.com, pjokk19940722
I/System.out: C: tag=4, command=CAPABILITY
    IMAP Line received : <4 CAPABILITY>
I/System.out: IMAP Line received : <
    >
    proxySelection = 2; no network service selected, use local service
    local service_ capability response: CAPABILITY IMAP4rev1 LITERAL+ SORT UIDPLUS
I/System.out: C: tag=5, command=NAMESPACE
I/System.out: IMAP Line received : <5 NAMESPACE>
I/System.out: C: tag=6, command=SELECT
    IMAP Line received : <6 SELECT >
I/System.out: IMAP Line received : <"Inbox"\r\n>
I/System.out: :::::::::: INBOX
    proxySelection = 2; no network service selected, use local service
    >>> Select <<<
W/System: A resource failed to call close. 
I/System.out: ^^^^^^^^^^^^^^^^^^^^^^^^
     Ding Ding
I/System.out: $$$$$$$$$$$$$$$$ check 1 $$$$$$$$$$$$$$$$
    $$$$$$$$$$$$$$$$ check 2 $$$$$$$$$$$$$$$$
I/System.out: -----------------------------------
I/System.out: $$$$$$$$$$$$$$$$ check 3 $$$$$$$$$$$$$$$$
    $$$$$$$$$$$$$$$$ check 4 $$$$$$$$$$$$$$$$
I/System.out: $$$$$$$$$$$$$$$$ check 5 $$$$$$$$$$$$$$$$
I/System.out: ############# check 1 ############# check 1
I/System.out: <><><><><><><><> Message size is: 77
I/System.out: ------------- Client -------------
I/System.out: ************* Google*************
I/System.out: C: tag=1, command=CAPABILITY
    IMAP Line received : <1 CAPABILITY>
    IMAP Line received : <
    >
    proxySelection = 2; no network service selected, use local service
I/System.out: local service_ capability response: CAPABILITY IMAP4rev1 LITERAL+ SORT UIDPLUS
I/System.out: ############# check 4 ############# check 4
    i ======== 0
I/System.out: C: tag=2, command=ID
I/System.out: IMAP Line received : <2 ID >
I/System.out: ************* Google*************
I/System.out: ------------- Client -------------
I/System.out: C: tag=3, command=LOGIN
    IMAP Line received : <3 LOGIN >
I/System.out: IMAP Line received : <jupan686@gmail.com "pjokk19940722"\r\n>
    Login: jupan686@gmail.com, pjokk19940722
I/System.out: i ======== 1
I/System.out: C: tag=1, command=CAPABILITY
I/System.out: IMAP Line received : <1 CAPABILITY>
    IMAP Line received : <
    >
    proxySelection = 2; no network service selected, use local service
    local service_ capability response: CAPABILITY IMAP4rev1 LITERAL+ SORT UIDPLUS
I/System.out: C: tag=2, command=ID
I/System.out: IMAP Line received : <2 ID >
I/System.out: i ======== 2
I/System.out: C: tag=3, command=LOGIN
    IMAP Line received : <3 LOGIN >
I/System.out: IMAP Line received : <jupan686@gmail.com "pjokk19940722"\r\n>
    Login: jupan686@gmail.com, pjokk19940722
I/System.out: i ======== 3
I/System.out: i ======== 4
I/System.out: i ======== 5
I/System.out: C: tag=4, command=CAPABILITY
I/System.out: IMAP Line received : <4 CAPABILITY>
    IMAP Line received : <
    >
    proxySelection = 2; no network service selected, use local service
    local service_ capability response: CAPABILITY IMAP4rev1 LITERAL+ SORT UIDPLUS
I/System.out: i ======== 6
I/System.out: C: tag=5, command=NAMESPACE
    IMAP Line received : <5 NAMESPACE>
I/System.out: C: tag=4, command=CAPABILITY
I/System.out: IMAP Line received : <4 CAPABILITY>
    IMAP Line received : <
    >
    proxySelection = 2; no network service selected, use local service
    local service_ capability response: CAPABILITY IMAP4rev1 LITERAL+ SORT UIDPLUS
I/System.out: i ======== 7
I/System.out: C: tag=6, command=SELECT
I/System.out: IMAP Line received : <6 SELECT >
    IMAP Line received : <"Inbox"\r\n>
I/System.out: :::::::::: INBOX
    proxySelection = 2; no network service selected, use local service
    >>> Select <<<
I/System.out: C: tag=5, command=NAMESPACE
    IMAP Line received : <5 NAMESPACE>
I/System.out: i ======== 8
I/System.out: C: tag=6, command=STATUS
    IMAP Line received : <6 STATUS >
I/System.out: IMAP Line received : <"[Gmail]/Sent Mail" (UIDVALIDITY)\r\n>
I/System.out: i ======== 9
I/System.out: C: tag=7, command=NOOP
    IMAP Line received : <7 NOOP>
I/System.out: IMAP Line received : <
    >
I/System.out: i ======== 10
I/System.out: C: tag=8, command=SELECT
    IMAP Line received : <8 SELECT >
I/System.out: IMAP Line received : <"[Gmail]/Sent Mail"\r\n>
I/System.out: i ======== 11
I/System.out: -----------------------------------
I/System.out: i ======== 12
I/System.out: i ======== 13
I/System.out: i ======== 14
I/System.out: ^^^^^^^^^^^^^^^^^^^^^^^^
     Ding Ding
    $$$$$$$$$$$$$$$$ check 1 $$$$$$$$$$$$$$$$
    $$$$$$$$$$$$$$$$ check 2 $$$$$$$$$$$$$$$$
I/System.out: i ======== 15
W/System.err: java.util.NoSuchElementException: Message does not belong to this folder
I/System.out: $$$$$$$$$$$$$$$$ check 3 $$$$$$$$$$$$$$$$
    $$$$$$$$$$$$$$$$ check 4 $$$$$$$$$$$$$$$$
    $$$$$$$$$$$$$$$$ check 5 $$$$$$$$$$$$$$$$
W/System.err:     at com.sun.mail.imap.IMAPFolder.getUID(IMAPFolder.java:2734)
        at com.icegreen.greenmail.ndnproxy.NdnFolder.getMessageUids(NdnFolder.java:103)
        at com.icegreen.greenmail.ndnproxy.NdnFolder.getMsn(NdnFolder.java:74)
        at com.icegreen.greenmail.ndnproxy.NdnFolder.getFirstUnseen(NdnFolder.java:123)
        at com.icegreen.greenmail.ndnproxy.NdnFolder.getSnapshot(NdnFolder.java:57)
        at com.icegreen.greenmail.imap.commands.SelectCommand.doProcess(SelectCommand.java:253)
        at com.icegreen.greenmail.imap.commands.CommandTemplate.process(CommandTemplate.java:61)
W/System.err:     at com.icegreen.greenmail.imap.ImapRequestHandler.doProcessRequest(ImapRequestHandler.java:103)
        at com.icegreen.greenmail.imap.ImapRequestHandler.handleRequest(ImapRequestHandler.java:52)
        at com.icegreen.greenmail.imap.ImapHandler.run(ImapHandler.java:71)
        at com.icegreen.greenmail.server.AbstractServer$1.run(AbstractServer.java:163)
        at java.lang.Thread.run(Thread.java:764)
I/System.out: C: tag=7, command=UID
I/System.out: IMAP Line received : <7 UID >
I/System.out: I am in Search Command!
I/System.out: IMAP Line received : <SEARCH 1:77 NOT DELETED\r\n>
I/System.out: C: tag=8, command=UID
    IMAP Line received : <8 UID >
I/System.out: IMAP Line received : <FETCH 481 (UID FLAGS INTERNALDATE RFC822.SIZE BODY.PEEK[HEADER.FIELDS (from reply-to to cc bcc content-type date message-id X-Android-Message-ID subject in-reply-to references)])\r\n>
    I am in Fetch Command!
W/System: A resource failed to call close. 
I/System.out: ############# check 1 ############# check 1
I/System.out: <><><><><><><><> Message size is: 77
I/System.out: ############# check 4 ############# check 4
    i ======== 0
I/System.out: i ======== 1
I/System.out: i ======== 2
I/System.out: i ======== 3
I/System.out: i ======== 4
I/System.out: i ======== 5
I/System.out: i ======== 6
I/System.out: i ======== 7
I/System.out: >>>> Fetching UID: 481
I/System.out: i ======== 8
W/System.err: java.util.NoSuchElementException: Message does not belong to this folder
        at com.sun.mail.imap.IMAPFolder.getUID(IMAPFolder.java:2734)
        at com.icegreen.greenmail.ndnproxy.NdnFolder.getMessageUids(NdnFolder.java:103)
        at com.icegreen.greenmail.ndnproxy.NdnFolder.getMsn(NdnFolder.java:74)
        at com.icegreen.greenmail.ndnproxy.NdnFolder.getFirstUnseen(NdnFolder.java:123)
        at com.icegreen.greenmail.ndnproxy.NdnFolder.getSnapshot(NdnFolder.java:57)
        at com.icegreen.greenmail.imap.commands.SelectCommand.doProcess(SelectCommand.java:253)
        at com.icegreen.greenmail.imap.commands.CommandTemplate.process(CommandTemplate.java:61)
        at com.icegreen.greenmail.imap.ImapRequestHandler.doProcessRequest(ImapRequestHandler.java:103)
        at com.icegreen.greenmail.imap.ImapRequestHandler.handleRequest(ImapRequestHandler.java:52)
        at com.icegreen.greenmail.imap.ImapHandler.run(ImapHandler.java:71)
W/System.err:     at com.icegreen.greenmail.server.AbstractServer$1.run(AbstractServer.java:163)
        at java.lang.Thread.run(Thread.java:764)
I/System.out: C: tag=7, command=UID
I/System.out: IMAP Line received : <7 UID >
I/System.out: IMAP Line received : <FETCH 481 (UID BODY.PEEK[2])\r\n>
    I am in Fetch Command!
```

**Comment by jupancs** [comment]
This happens when you first install the app and run it.
